name: SonarQube

runs:
  using: composite

  steps:
    - name: SonarQube Scan
      shell: bash
      run: |
        npm install
        npx sonar-scanner \
          -Dsonar.projectKey=demo-app \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
          -Dsonar.token=${{ env.SONAR_TOKEN }}
