name: Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: Select Branch
        required: true
        type: choice
        options:
          - release-1.0
          - release-2.0
          - QA

      run_scm:
        description: Run SCM Scan
        required: true
        type: boolean
        default: true

      run_sast:
        description: Run SAST Scan
        required: true
        type: boolean
        default: true

jobs:

  sit:
    uses: ./.github/workflows/sit.yml
    with:
      target_branch: ${{ inputs.target_branch }}
      run_scm: ${{ inputs.run_scm }}
      run_sast: ${{ inputs.run_sast }}

  qa:
    needs: sit
    uses: ./.github/workflows/qa.yml
    with:
      target_branch: ${{ inputs.target_branch }}
      run_scm: ${{ inputs.run_scm }}
      run_sast: ${{ inputs.run_sast }}

  uat:
    needs: qa
    uses: ./.github/workflows/uat.yml
    with:
      target_branch: ${{ inputs.target_branch }}
      run_scm: ${{ inputs.run_scm }}
      run_sast: ${{ inputs.run_sast }}
