name: QA

on:
  workflow_call:
    inputs:
      target_branch:
        required: true
        type: string

      run_scm:
        required: true
        type: boolean

      run_sast:
        required: true
        type: boolean

jobs:
  qa:
    runs-on: ubuntu-latest
    environment: QA

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_branch }}

      - name: Install Dependencies
        run: npm install

      - name: Validate App
        run: node --check app.js
