name: SIT

on:
  workflow_call:
    inputs:
      target_branch:
        required: true
        type: string

      #run_scm:
        #required: true
        #type: boolean

      #run_sast:
        #required: true
        #type: boolean

jobs:
  sit:
    runs-on: ubuntu-latest
    environment: SIT

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_branch }}

      - name: Display Branch Information
        run: |
          echo "Workflow Branch: ${{ github.ref_name }}"
          echo "Selected Branch: ${{ inputs.target_branch }}"


      - name: SCM
        if: ${{ inputs.run_scm }}
        uses: ./.github/actions/scm

      - name: SAST
        if: ${{ inputs.run_sast }}
        uses: ./.github/actions/sast

      - name: Start Application
        run: |
          npm install
          node app.js &
          sleep 10

      - name: Checkout Functional Tests
        uses: actions/checkout@v4
        with:
          ref: katalon
          path: katalon

      - name: Smoke Test
        run: |
          chmod +x katalon/smoke-tests/smoke-test.sh
          ./katalon/smoke-tests/smoke-test.sh

      - name: Product Test
        run: |
          chmod +x katalon/product-tests/product-test.sh
          ./katalon/product-tests/product-test.sh

      - name: Navigation Test
        run: |
          chmod +x katalon/navigation-tests/navigation-test.sh
          ./katalon/navigation-tests/navigation-test.sh

      - name: Install Dependencies
        run: npm install

      - name: Validate App
        run: node --check app.js

      - name: Verify Files
        run: |
          ls -la
          test -f app.js
          test -f package.json
