name: SIT

on:
  workflow_call:
    inputs:
      target_branch:
        required: true
        type: string

      run_scm:
        required: true
        type: boolean

      run_sast:
        required: true
        type: boolean

jobs:
  sit:
    runs-on: ubuntu-latest
    environment: SIT

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_branch }}

      - name: SCM
        if: ${{ inputs.run_scm }}
        uses: ./.github/actions/scm

      - name: SAST
        if: ${{ inputs.run_sast }}
        uses: ./.github/actions/sast

      - name: Install Dependencies
        run: npm install

      - name: Validate App
        run: node --check app.js

      - name: Verify Files
        run: |
          ls -la
          test -f app.js
          test -f package.json
