name: UAT

on:
  workflow_call:
    inputs:
      target_branch:
        required: true
        type: string

jobs:
  uat:
    runs-on: ubuntu-latest
    environment: UAT

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_branch }}

      - name: Install Dependencies
        run: npm install

      - name: Validate App
        run: node --check app.js
